Repository prgrms-be-devcourse/BE-04-GosuCatcher, pull requests merged in 2023-09, with the labels that each got.

#21 [GS-49] 정렬/페이징 처리
  src/main/java/com/foo/gosucatcher/domain/bucket/application/BucketService.java
  src/main/java/com/foo/gosucatcher/domain/bucket/domain/Bucket.java
  src/main/java/com/foo/gosucatcher/domain/bucket/domain/BucketRepository.java
  src/main/java/com/foo/gosucatcher/domain/bucket/dto/request/BucketRequest.java
  src/main/java/com/foo/gosucatcher/domain/bucket/dto/response/BucketResponse.java
  src/main/java/com/foo/gosucatcher/domain/bucket/dto/response/BucketsResponse.java
  src/main/java/com/foo/gosucatcher/domain/bucket/presentation/BucketController.java
  src/main/java/com/foo/gosucatcher/domain/review/application/ReviewService.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReviewResponse.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReviewsResponse.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/Review.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/ReviewRepository.java
  src/main/java/com/foo/gosucatcher/domain/review/presentation/ReviewController.java
  src/test/java/com/foo/gosucatcher/domain/bucket/presentation/BucketControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/review/presentation/ReviewControllerTest.java
Labels: Sprint_2

#20 [GS-62] 메인 서비스에 포함된 세부 서비스들 조회
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertResponseEstimate.java
  src/main/java/com/foo/gosucatcher/domain/item/application/MainItemService.java
  src/main/java/com/foo/gosucatcher/domain/item/application/SubItemService.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/MainItemCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/MainItemUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/SubItemCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/SubItemUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/main/MainItemCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/main/MainItemUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/sub/SubItemCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/request/sub/SubItemUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/MainItemResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/MainItemsResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/SubItemResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/SubItemsResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/main/MainItemResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/main/MainItemsResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/sub/SubItemResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/sub/SubItemSliceResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/sub/SubItemsResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/sub/SubItemsSliceResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/MainItem.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/MainItemRepository.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/SubItem.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/SubItemRepository.java
  src/main/java/com/foo/gosucatcher/domain/item/presentation/MainItemController.java
  src/main/java/com/foo/gosucatcher/domain/item/presentation/SubItemController.java
  src/test/java/com/foo/gosucatcher/domain/item/application/MainItemServiceUnitTest.java
  src/test/java/com/foo/gosucatcher/domain/item/application/SubItemServiceUnitTest.java
  src/test/java/com/foo/gosucatcher/domain/item/presentation/MainItemControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/item/presentation/SubItemControllerTest.java
Labels: Sprint_2

#22 [GS-56] 리뷰에 대한 답글
  src/main/java/com/foo/gosucatcher/domain/bucket/domain/Bucket.java
  src/main/java/com/foo/gosucatcher/domain/bucket/presentation/BucketController.java
  src/main/java/com/foo/gosucatcher/domain/review/application/ReviewService.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReplyRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReviewCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReviewUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReplyResponse.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReviewResponse.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/Reply.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/ReplyRepository.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/Review.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/ReviewRepository.java
  src/main/java/com/foo/gosucatcher/domain/review/presentation/ReviewController.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/main/java/com/foo/gosucatcher/global/error/exception/UnsupportedReplierException.java
  src/test/java/com/foo/gosucatcher/domain/bucket/presentation/BucketControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/review/presentation/ReviewControllerTest.java
Labels: Sprint_2

#24 [GS-53] 회원 권한 및 JWT 구현 후 가입, 로그인/로그아웃, 탈퇴
  build.gradle
  src/main/java/com/foo/gosucatcher/GosuCatcherApplication.java
  src/main/java/com/foo/gosucatcher/config/SecurityConfigure.java
  src/main/java/com/foo/gosucatcher/config/WebMvcConfigure.java
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberLoginRequest.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberProfileChangeRequest.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberRefreshRequest.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberSignupRequest.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberCertifiedResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberEmailDuplicateResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberLogInResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberProfileChangeResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberProfileResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/MemberSignupResponse.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/Roles.java
  src/main/java/com/foo/gosucatcher/domain/member/exception/MemberCertifiedFailException.java
  src/main/java/com/foo/gosucatcher/domain/member/infrastructure/MemberProfileFileSystemRepository.java
  src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberEmail.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberEmailAop.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberId.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberIdAop.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/main/java/com/foo/gosucatcher/global/security/CustomUserDetailsService.java
  src/main/java/com/foo/gosucatcher/global/security/JwtAccessTokenFilter.java
  src/main/java/com/foo/gosucatcher/global/security/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/foo/gosucatcher/domain/member/application/MemberServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/member/presentation/MemberControllerTest.java
Labels: Sprint_2

#23 [GS-54] 고수 이미지 처리
  build.gradle
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImage.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImageRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/exception/ExpertImageIOException.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/domain/image/ImageService.java
  src/main/java/com/foo/gosucatcher/domain/image/application/dto/request/ImageUploadRequest.java
  src/main/java/com/foo/gosucatcher/domain/image/application/dto/response/ImageResponse.java
  src/main/java/com/foo/gosucatcher/domain/image/application/dto/response/ImageUploadResponse.java
  src/main/java/com/foo/gosucatcher/domain/image/domain/Image.java
  src/main/java/com/foo/gosucatcher/domain/image/infrastructure/FileSystemExpertImageService.java
  src/main/java/com/foo/gosucatcher/global/util/ImageFileUtils.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
Labels: Sprint_2

#26 [GS-70] 고수가 제공할 서비스 등록/삭제, 해당 고수가 보유한 서비스 조회 구현
  src/main/java/com/foo/gosucatcher/domain/estimate/application/ExpertEstimateService.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/dto/request/ExpertSubItemRequest.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItem.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItemRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/domain/item/application/MainItemService.java
  src/main/java/com/foo/gosucatcher/domain/item/application/SubItemService.java
  src/main/java/com/foo/gosucatcher/domain/item/application/dto/response/sub/SubItemsResponse.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/MainItem.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/SubItem.java
  src/main/java/com/foo/gosucatcher/domain/item/domain/SubItemRepository.java
  src/main/java/com/foo/gosucatcher/domain/item/presentation/SubItemController.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/test/java/com/foo/gosucatcher/domain/expert/application/ExpertServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/item/application/SubItemServiceUnitTest.java
Labels: Sprint_2

#32 [GS-58] 일반 견적 처리 기능 구현
  src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/ExpertEstimateService.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberEstimateService.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/response/MemberEstimateResponse.java
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberEstimate.java
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/Status.java
  src/main/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateController.java
  src/main/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateController.java
  src/main/java/com/foo/gosucatcher/domain/matching/application/MatchingService.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java
Labels: Sprint_2

#29 [GS-60] 고수 서비스,지역 None 리뷰순 조회
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
Labels: Sprint_2

#33 [GS-61] 고수 서비스,지역 None 평점순 조회
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/ExpertResponse.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/SlicedExpertsResponse.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/SortType.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
Labels: Sprint_2

#31 [GS-67] 리뷰 관련 개선
  src/main/java/com/foo/gosucatcher/domain/bucket/application/BucketService.java
  src/main/java/com/foo/gosucatcher/domain/bucket/domain/Bucket.java
  src/main/java/com/foo/gosucatcher/domain/bucket/presentation/BucketController.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/domain/review/application/ReviewService.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReplyRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReviewCreateRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/request/ReviewUpdateRequest.java
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReviewResponse.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/Reply.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/Review.java
  src/main/java/com/foo/gosucatcher/domain/review/domain/ReviewRepository.java
  src/main/java/com/foo/gosucatcher/domain/review/presentation/ReviewController.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/main/java/com/foo/gosucatcher/global/error/exception/InvalidReplyCountException.java
  src/main/java/com/foo/gosucatcher/global/error/exception/UnsupportedBucketException.java
  src/main/java/com/foo/gosucatcher/global/error/exception/UnsupportedUpdateException.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/review/presentation/ReviewControllerTest.java
Labels: Sprint_2

#35 [GS-74] 서비스 인기 검색어 목록 구현
  src/main/java/com/foo/gosucatcher/config/RedisConfig.java
  src/main/java/com/foo/gosucatcher/domain/search/application/SearchService.java
  src/main/java/com/foo/gosucatcher/domain/search/application/dto/response/SearchRankingListResponse.java
  src/main/java/com/foo/gosucatcher/domain/search/application/dto/response/SearchRankingResponse.java
  src/main/java/com/foo/gosucatcher/domain/search/presentation/SearchController.java
  src/test/java/com/foo/gosucatcher/domain/search/presentation/SearchControllerTest.java
Labels: Sprint_3

#36 [GS-89] 바로 매칭 서비스 N+1 쿼리 최적화
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/response/ChattingRoomResponse.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/response/ExpertAutoEstimatesResponse.java
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertEstimateRepository.java
Labels: Sprint_3

#38 [GS-90] 고수 도메인 내 이미지 관련 코드 리팩토링
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImage.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImageRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItemRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/domain/image/application/dto/response/ImageResponse.java
  src/main/java/com/foo/gosucatcher/domain/image/domain/Image.java
  src/main/java/com/foo/gosucatcher/domain/image/infrastructure/FileSystemExpertImageService.java
  src/main/java/com/foo/gosucatcher/global/error/exception/ImageIOException.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
Labels: Sprint_3

#37 [GS-85] 웹 소켓 채팅 기능 구현
  build.gradle
  src/main/java/com/foo/gosucatcher/config/SecurityConfig.java
  src/main/java/com/foo/gosucatcher/config/WebSocketConfig.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/ChattingRoomService.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/request/MessageRequest.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/response/MessageResponse.java
  src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingRoom.java
  src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingStatus.java
  src/main/java/com/foo/gosucatcher/domain/chat/domain/Message.java
  src/main/java/com/foo/gosucatcher/domain/chat/infrastructure/WebSocketChatHandler.java
  src/main/java/com/foo/gosucatcher/domain/chat/presentation/ChattingRoomController.java
  src/test/java/com/foo/gosucatcher/domain/chat/application/ChattingRoomServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/chat/application/MessageServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/chat/presentation/ChattingRoomControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java
Labels: Sprint_3

#42 [GS-91] 웹소켓 채팅 -> STOMP + JWT 토큰 검증으로 고도화
  src/main/java/com/foo/gosucatcher/config/SecurityConfig.java
  src/main/java/com/foo/gosucatcher/config/StompHandler.java
  src/main/java/com/foo/gosucatcher/config/WebMvcConfig.java
  src/main/java/com/foo/gosucatcher/config/WebSocketConfig.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/ChattingRoomService.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/request/MessageRequest.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/response/MessageResponse.java
  src/main/java/com/foo/gosucatcher/domain/chat/domain/Message.java
  src/main/java/com/foo/gosucatcher/domain/chat/infrastructure/WebSocketChatHandler.java
  src/main/java/com/foo/gosucatcher/domain/chat/presentation/MessageController.java
  src/main/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateController.java
  src/main/java/com/foo/gosucatcher/domain/matching/application/MatchingService.java
Labels: Sprint_3

#44 [GS-80] 유저 프로필 이미지 클래스 리팩토링
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
  src/main/java/com/foo/gosucatcher/domain/image/domain/Image.java
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberProfileService.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/ImageFile.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/MemberImage.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/MemberProfileRepository.java
  src/main/java/com/foo/gosucatcher/domain/member/infrastructure/MemberProfileFileSystemRepository.java
  src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberProfileController.java
  src/main/java/com/foo/gosucatcher/global/util/ImageFileUtils.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/member/presentation/MemberControllerTest.java
Labels: Sprint_3

#43 [GS-88] 견적서 & 채팅방 조회, 검증 기능 추가
  src/main/java/com/foo/gosucatcher/domain/chat/application/ChattingRoomService.java
  src/main/java/com/foo/gosucatcher/domain/chat/presentation/ChattingRoomController.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/ExpertEstimateService.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberEstimateService.java
  src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/response/MemberEstimateResponse.java
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertEstimateRepository.java
  src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberEstimateRepository.java
  src/main/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateController.java
  src/main/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateController.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItemRepository.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/test/java/com/foo/gosucatcher/domain/chat/application/ChattingRoomServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/chat/presentation/ChattingRoomControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/application/ExpertEstimateServiceUnitTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/application/MemberEstimateServiceTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java
Labels: Sprint_3

#45 [GS-105] 요청서-견적서 Message 서비스 리팩토링
  src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
  src/main/java/com/foo/gosucatcher/domain/chat/application/dto/request/MessageRequest.java
Labels: Sprint_4

#47 [GS-106] 토큰 검증 + AOP 리팩토링
  build.gradle
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberAuthService.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentExpertIdAop.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberEmailAop.java
  src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberIdAop.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
  src/main/java/com/foo/gosucatcher/global/error/ErrorResponse.java
  src/main/java/com/foo/gosucatcher/global/error/exception/JwtTokenException.java
  src/main/java/com/foo/gosucatcher/global/security/CustomUserDetails.java
  src/main/java/com/foo/gosucatcher/global/security/CustomUserDetailsService.java
  src/main/java/com/foo/gosucatcher/global/security/JwtAuthenticationFilter.java
  src/main/java/com/foo/gosucatcher/global/security/JwtTokenProvider.java
Labels: Sprint_4

#48 [GS-93] 메인 화면 구성 (nav,header,footer)
  build.gradle
  src/main/java/com/foo/gosucatcher/view/HomeController.java
  src/main/java/com/foo/gosucatcher/view/item/ItemController.java
  src/main/resources/static/img/banner.png
  src/main/resources/templates/home.html
  src/main/resources/templates/items/items.html
  src/main/resources/templates/layout/nav.html
Labels: Sprint_4

#49 [GS-95] 회원가입 화면 구성 + 회원가입시 이메일 검증 추가
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberAuthService.java
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberEmailAuthService.java
  src/main/java/com/foo/gosucatcher/domain/member/domain/MemberEmailRequest.java
  src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberEmailAuthController.java
  src/main/java/com/foo/gosucatcher/view/item/ItemViewController.java
  src/main/java/com/foo/gosucatcher/view/members/MemberViewController.java
  src/main/resources/static/js/members/member.js
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/members/joinForm.html
Labels: Sprint_4

#51 [GS-109] 견적 요청서 화면 구성
  src/main/java/com/foo/gosucatcher/view/estimate/MemberEstimateViewController.java
  src/main/resources/static/css/estimates/member-estimate.css
  src/main/resources/static/js/estimates/member-estimate.js
  src/main/resources/templates/estimate/member-estimate.html
Labels: Sprint_4

#52 [GS-110] 바로 견적 요청서 화면 구성 & 일반 견적 요청서 수정
  src/main/java/com/foo/gosucatcher/view/estimate/MemberEstimateViewController.java
  src/main/resources/static/js/estimates/auto-member-estimate.js
  src/main/resources/static/js/estimates/normal-member-estimate.js
  src/main/resources/templates/estimates/auto-member-estimate.html
  src/main/resources/templates/estimates/normal-member-estimate.html
Labels: Sprint_4

#53 [GS-97] 고수 프로필 화면
  src/main/java/com/foo/gosucatcher/view/expert/ExpertViewController.java
  src/main/resources/static/img/cat.jpeg
  src/main/resources/static/img/dog.jpeg
  src/main/resources/templates/experts/experts.html
Labels: Sprint_4

#54 [GS-94] 로그인 화면 구현 및 로그인 성공, 토큰 로컬스토리지 저장, 메인페이지 리다이렉션
  src/main/java/com/foo/gosucatcher/domain/member/application/MemberAuthService.java
  src/main/java/com/foo/gosucatcher/view/members/MemberViewController.java
  src/main/resources/static/css/common/common-style.css
  src/main/resources/static/css/members/joinForm-style.css
  src/main/resources/static/css/members/login-style.css
  src/main/resources/static/js/common/nav.js
  src/main/resources/static/js/members/login.js
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/members/joinForm.html
  src/main/resources/templates/members/login.html
Labels: Sprint_4

#60 [GS-98] 고수 찾기 화면
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/ExpertResponse.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/java/com/foo/gosucatcher/view/expert/ExpertViewController.java
  src/main/resources/static/img/white.png
  src/main/resources/static/js/experts/experts-search.js
  src/main/resources/templates/experts/experts-search.html
  src/main/resources/templates/experts/experts.html
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java
  src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java
Labels: Sprint_4

#62 [GS-119] 최근 검색 + 인기 검색 화면
  src/main/resources/static/js/search/search.js
  src/main/resources/templates/estimates/auto-member-estimate.html
  src/main/resources/templates/layout/nav.html
Labels: Sprint_4

#63 [GS-125] 채팅방 리스트 화면
  src/main/java/com/foo/gosucatcher/view/chat/ChatViewController.java
  src/main/resources/data.sql
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/chats.html
Labels: Sprint_4

#64 [GS-121] 고수 일반 견적서 화면 구성
  src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberProfileController.java
  src/main/java/com/foo/gosucatcher/view/estimate/ExpertEstimateViewController.java
  src/main/resources/static/css/estimates/normal-expert-estimate.css
  src/main/resources/static/js/estimates/normal-expert-estimate.js
  src/main/resources/templates/estimates/auto-expert-estimate.html
  src/main/resources/templates/estimates/normal-expert-estimate.html
Labels: Sprint_4

#65 [GS-123] 고수 프로필 화면 및 고수 찾기 화면 리팩토링
  src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
  src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
  src/main/resources/static/css/experts/experts-search.css
  src/main/resources/static/css/experts/experts.css
  src/main/resources/static/img/cat.jpeg
  src/main/resources/static/img/dog.jpeg
  src/main/resources/static/js/experts/experts-search.js
  src/main/resources/static/js/experts/experts.js
  src/main/resources/templates/experts/experts-search.html
  src/main/resources/templates/experts/experts.html
  src/main/resources/templates/layout/nav.html
Labels: Sprint_4

#66 [GS-118] 고수 검색후 상세조회
  src/main/java/com/foo/gosucatcher/domain/review/application/dto/response/ReviewResponse.java
  src/main/java/com/foo/gosucatcher/view/expert/ExpertViewController.java
  src/main/resources/static/css/experts/profile.css
  src/main/resources/static/css/main.css
  src/main/resources/static/js/experts/profile.js
  src/main/resources/static/js/members/member.js
  src/main/resources/static/js/members/my-page.js
  src/main/resources/templates/experts/profile.html
  src/main/resources/templates/members/my-page.html
Labels: Sprint_4

#70 [GS-128] 레스트 독스 - 회원 견적서
  src/docs/asciidoc/memberEstimate.adoc
  src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java
Labels: Sprint_4
